services:
  database:
    image: postgres:alpine
    ports: 
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    volumes:
    - ./data:/var/lib/postgresql/data